service: serverless-project-name

provider:
  name: aws
  runtime: nodejs10.x
  region: region, 'us-east-1'
  memorySize: 256
  timeout: 3
  stage: "dev"
  environment:
    SECRET: test-secret

functions:
  - ${file(./src/controller/user/user.yml)}
  - ${file(./src/controller/weather/weather.yml)}
  - ${file(./test.yml)}
 

plugins:
  - serverless-plugin-typescript
  - serverless-offline
