service: serverless-project-name

custom:
  serverless-offline:
    port: 3001

# provider:
#   name: aliyun
#   runtime: nodejs10
#   credentials: ~/.aliyun/credentials
#   timeout: 600

provider:
  name: aws
  runtime: nodejs10.x
  region:  us-east-2
  memorySize: 256
  timeout: 3
  stage: dev


functions:
  # - ${file(./src/controller/user/user.yml)}
  - ${file(./src/controller/weather/weather.yml)}
  # - ${file(./test.yml)}

plugins:
  - serverless-offline
  - serverless-plugin-typescript
